sudo: required
services: 
    - docker

before_install:
    - docker build -t weizai133/react-test -f ./client/Dockerfile.dev ./client

script:
     - docker run -e CI=true weizai133/react-test npm test -- --coverage
    
after_success:
    - docker build -t weizai133/complex-client ./client
    - docker build -t weizai133/complex-nginx ./nginx
    - docker build -t weizai133/complex-server ./server
    - docker build -t weizai133/complex-worker ./worker
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push weizai133/complex-client
    - docker push weizai133/complex-nginx
    - docker push weizai133/complex-server
    - docker push weizai133/complex-worker